import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';
import {
  M_PLUS_Rounded_1c,
  Jura,
  Sofia_Sans_Extra_Condensed,
} from 'next/font/google';

// Google fonts
const mPlusRounded = M_PLUS_Rounded_1c({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-plus',
});

const jura = Jura({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jura',
});

const sofiaSansExtraCondensed = Sofia_Sans_Extra_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sofia',
});

// Local fonts
const PFBaselinePro = localFont({
  src: [
    {
      path: '../fonts/PFBaselinePro-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/PFBaselinePro-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/PFBaselinePro-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pro',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body
        className={`${mPlusRounded.variable} ${jura.variable} ${sofiaSansExtraCondensed.variable} ${PFBaselinePro.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
